name: nexus
description: The IIT Bombay Nexus App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Backend & Navigation
  supabase_flutter: ^2.8.0
  go_router: ^14.0.0

  # UI & Design
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation (Required for Riverpod)
  build_runner: ^2.4.9
  riverpod_generator: ^2.6.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true